Django/belt_reviewer/apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^register$', views.register),
    url(r'^login$', views.login, name = 'login'),
    url(r'^logout$', views.logout, name = 'logout'),
    url(r'^user/(?P<user_id>\d+)$', views.profile)
]

Django/belt_reviewer/apps/review/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^add$', views.add, name = 'add'),
    url(r'^create', views.create, name = 'create'),
    url(r'^(?P<book_id>\d+)$', views.display),
    url(r'^(?P<book_id>\d+)/create$', views.create_addl),
]

Django/belt_reviewer/belt_reviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include ('apps.login.urls', namespace = 'login')),
    url(r'^books/', include ('apps.review.urls', namespace = 'review')),
]

Django/belt_reviewer/apps/login/models.py
from __future__ import unicode_literals
import re
import bcrypt
from django.db import models

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')


class UserManager(models.Manager):
    def validate_login(self, post_data):
        errors = []

        if len(self.filter(email = post_data['email'])) > 0:

            user = self.filter(email = post_data['email'])[0]
            if not bcrypt.checkpw(post_data['password'].encode(), user.password.encode()):
                errors.append('Password is incorrect')
        else:
            errors.append('Email and/or password incorrect')
        if errors:
            return errors
        return user

    def validate_registration(self, post_data):
        errors = []

        if len(post_data['name'])<3 or len(post_data['alias'])<3:
            errors.append("Please enter Name's with at least 3 characters.")
        if not re.match(NAME_REGEX, post_data['name']) or not re.match(NAME_REGEX, post_data['alias']):
            errors.append("Please enter Name's with only letters")


        if not re.match(EMAIL_REGEX, post_data['email']):
            errors.append("Invalid email")
        if len(User.objects.filter(email=post_data['email'])) > 0:
            errors.append("Email already in use")


        if len(post_data['password'])<8:
            errors.append("Please enter a Password with at least 8 characters.")
        if post_data['confirm_pw'] != post_data['password']:
            errors.append("Passwords do not match.")

        if not errors:
            
            hashed = bcrypt.hashpw((post_data['password'].encode()), bcrypt.gensalt(5))

            new_user = self.create(
                name = post_data['name'],
                alias = post_data ['alias'],
                email = post_data ['email'],
                password = hashed
            )
            return new_user
        return errors

class User(models.Model):
    name = models.CharField(max_length = 255)
    alias = models.CharField(max_length = 255)
    email = models.EmailField(unique = True)
    password = models.CharField(max_length = 255)
    objects = UserManager()
    def __str__(self):
        return self.email

Django/belt_reviewer/apps/login/views.py
from __future__ import unicode_literals
from django.contrib.messages import error
from django.shortcuts import render, HttpResponse, redirect, reverse, HttpResponseRedirect
from .models import *
from ..review.models import Book, Author, Review
from django.contrib import messages

def index(request):
    return render (request, "login/index.html")

def register(request):
    result = User.objects.validate_registration(request.POST)
    if type(result) == list:
        for err in result:
            messages.error(request, err)
        return redirect('/')
    request.session['user_id'] = result.id
    return HttpResponseRedirect(reverse("review:home"))

def login(request):
    result = User.objects.validate_login(request.POST)
    if type(result) == list:
        for err in result:
            messages.error(request, err)
        return redirect('/')
    request.session['user_id'] = result.id
    return HttpResponseRedirect(reverse("review:home"))


def profile(request, user_id):
    user = User.objects.get(id=user_id)
    unique_ids= user.reviews_left.all().values("book").distinct()
    unique_books=[]
    for book in unique_ids:
        unique_books.append(Book.objects.get(id=book['book']))
    context={
        'user': user,
        'unique_book_reviews': unique_books
    }
    return render(request, "login/profile.html", context)
    return HttpResponse ("Profile info")

def logout(request):
    for key in request.session.keys():
        del request.session[key]
    return redirect('/')

Django/belt_reviewer/apps/login/templates/login/add.html
<!doctype html>
<html>
  <head>
    <title>Belt Reviewer</title>
  </head>
  <body>
    <div>
      <h4><a href = "/home">Home</a></h4>
      <h4><a href = "/logout">Logout</a></h4>
    </div>
    <h4>Add a New Book Title and a Review:</h4>
    {% if messages %}
      {% for message in messages %}
        <p>{{ messages }}</p>
      {% endfor %}
    {% endif %}
    <form action = "/create" method = "POST">
      {% csrf_token %}
        <label for "title">Book Title:</label>
        <input type = "text"  name = "title">
        <label for "author">Author:</label>
        <input type = "text"  name = "author">
        <label for "review">Review: </label>
        <textarea name = "review"></textarea>
        <p><label for "rating" placeholder = "rate">Rating: </label>
        <select name = "rating" placeholder = "rate">
          <option value = "Select" selected disabled>Please Select</option>
          <option value = "1">1</option>
          <option value = "2">2</option>
          <option value = "3">3</option>
          <option value = "4">4</option>
          <option value = "5">5</option>
        </select> stars</p>
      <button type = "submit">Add Book and Review</button>
    </form>
  </body>
</html>
  

Django/belt_reviewer/apps/login/templates/login/index.html
<!doctype html>
<html>
  <head>
    <title>Belt Reviewer</title>
  </head>
  <body>
    <h1>Welcome!</h1>
  <div class="register">
    <h2>Register</h2>
    {% if messages %}
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    {% endif %}
    <form action="/register" method="post">
      {% csrf_token %}
      <label for "name">Name:</label>
      <input type= "text" name= "name">
      <label for "alias">Alias:</label>
      <input type= "text" name= "alias">
      <label for "email">Email:</label>
      <input type= "text" name= "email">
      <label for "password">Password:</label>
      <input type= "password" name= "password">
      <p>*Password should be at least 8 characters
      <label for "confirm_password">Confirm Password:</label>
      <input type= "password" name= "confirm_pw">
      <button class = "submit">Register</button>
    </form>
  </div>
  <div class="login">
    <h2>Login</h2>
    <form action="{% url 'login:login' %}" method="post">
      {% csrf_token %}
      <label for "email">Email:</label>
      <input type= "text" name= "email">
      <label for "password">Password:</label>
      <input type= "password" name= "password">
      <button class = "submit">Login</button>
    </form>
  </div>
  </body>
</html>

Django/belt_reviewer/apps/login/templates/login/profile.html
<html>
  <head>
    <title>Belt Reviewer</title>
  </head>
  <body>
    <div class = "heading">
      <p><a href="/books">Home</a> | <a href="{% url 'review:add' %}">Add a Book and Review</a> | <a href="/logout">Logout</a></p>
      <hr>
        <h2>User Alias: {{ user.alias }}</h2>
        <h4>Name: {{ user.name }}</h4>
        <h4>Email: {{ user.email }}</h4>
        <h4>Total Reviews: {{ user.reviews_left.all.count }}</h4>
        <h2>Posted Reviews on the Following Books:</h2>
          {% for book in unique_book_reviews %}
            <h5><a href="/books/{{book.id}}">{{book.title}}</a></h5>
          {% endfor %}
      </hr>
    </div>
  </body>
</html>